const actionTypes = {
  FETCH_ALL_TASKS: "FETCH_ALL_TASKS",
  FETCH_ERROR: "FETCH_ERROR",
  TASK_ADDED: "TASK_ADDED",
  POST_ERROR: "POST_ERROR",
  TASK_DELETED: "TASK_DELETED",
  DELETE_ERROR: "DELETE_ERROR",
  TASK_UPDATED: "TASK_UPDATED",
  UPDATE_ERROR: "UPDATE_ERROR"
};

export default actionTypes;
